// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: ringaroundtherosie.proto

package ringaroundtherosie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RingAroundTheRosieClient is the client API for RingAroundTheRosie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RingAroundTheRosieClient interface {
	// Sends a greeting
	GetRose(ctx context.Context, in *RoseRequest, opts ...grpc.CallOption) (*RoseResponse, error)
}

type ringAroundTheRosieClient struct {
	cc grpc.ClientConnInterface
}

func NewRingAroundTheRosieClient(cc grpc.ClientConnInterface) RingAroundTheRosieClient {
	return &ringAroundTheRosieClient{cc}
}

func (c *ringAroundTheRosieClient) GetRose(ctx context.Context, in *RoseRequest, opts ...grpc.CallOption) (*RoseResponse, error) {
	out := new(RoseResponse)
	err := c.cc.Invoke(ctx, "/ringaroundtherosie.RingAroundTheRosie/GetRose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RingAroundTheRosieServer is the server API for RingAroundTheRosie service.
// All implementations must embed UnimplementedRingAroundTheRosieServer
// for forward compatibility
type RingAroundTheRosieServer interface {
	// Sends a greeting
	GetRose(context.Context, *RoseRequest) (*RoseResponse, error)
	mustEmbedUnimplementedRingAroundTheRosieServer()
}

// UnimplementedRingAroundTheRosieServer must be embedded to have forward compatible implementations.
type UnimplementedRingAroundTheRosieServer struct {
}

func (UnimplementedRingAroundTheRosieServer) GetRose(context.Context, *RoseRequest) (*RoseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRose not implemented")
}
func (UnimplementedRingAroundTheRosieServer) mustEmbedUnimplementedRingAroundTheRosieServer() {}

// UnsafeRingAroundTheRosieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RingAroundTheRosieServer will
// result in compilation errors.
type UnsafeRingAroundTheRosieServer interface {
	mustEmbedUnimplementedRingAroundTheRosieServer()
}

func RegisterRingAroundTheRosieServer(s grpc.ServiceRegistrar, srv RingAroundTheRosieServer) {
	s.RegisterService(&RingAroundTheRosie_ServiceDesc, srv)
}

func _RingAroundTheRosie_GetRose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RingAroundTheRosieServer).GetRose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ringaroundtherosie.RingAroundTheRosie/GetRose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RingAroundTheRosieServer).GetRose(ctx, req.(*RoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RingAroundTheRosie_ServiceDesc is the grpc.ServiceDesc for RingAroundTheRosie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RingAroundTheRosie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ringaroundtherosie.RingAroundTheRosie",
	HandlerType: (*RingAroundTheRosieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRose",
			Handler:    _RingAroundTheRosie_GetRose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ringaroundtherosie.proto",
}
